### ISSUE TITLE
Syncronize legacy doc TLS page with nextgen docs

### ISSUE THREAD

**Issue by ravindk89** [minio/docs#440] opened 2022-03-16 22:33 UTC
**Summary**

The [legacy docs](https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html) page contains some information not fully captured in the [next gen docs](https://docs.min.io/minio/baremetal/security/network-encryption/minio-tls.html). For example, tutorials on using MinIO's certbot or the acceptable formats for certificates 

**Goals**

List the in-scope goals

- [ ] Review the legacy docs for content missing in the next gen docs
- [ ] Add new content as necessary
- [ ] Validate any new tutorials

**Non-Goals**

Creating production-grade TLS certs isn't in scope here. It's sufficient for certificates to work in development environments only.

**Additional context**

**Comment by djwfyi** [comment] 2022-09-28 19:13
Effectively a duplicate of #310 .

**Closed by djwfyi** 2022-09-28 19:13 UTC
Labels: priority: medium
